"use strict";

const {REST_VERSION} = require("../Constants");

module.exports.BASE_URL = "/api/v" + REST_VERSION;
module.exports.CDN_URL = "https://constanze.live";
module.exports.CLIENT_URL = "https://constanze.live";

module.exports.CHANNEL =                                                (chanID) => `/channels/${chanID}`;
module.exports.CHANNEL_BULK_DELETE =                                    (chanID) => `/channels/${chanID}/messages/bulk-delete`;
module.exports.CHANNEL_CALL_RING =                                      (chanID) => `/channels/${chanID}/call/ring`;
module.exports.CHANNEL_CROSSPOST =                               (chanID, msgID) => `/channels/${chanID}/messages/${msgID}/crosspost`;
module.exports.CHANNEL_FOLLOW =                                         (chanID) => `/channels/${chanID}/followers`;
module.exports.CHANNEL_INVITES =                                        (chanID) => `/channels/${chanID}/invites`;
module.exports.CHANNEL_MESSAGE_REACTION =              (chanID, msgID, reaction) => `/channels/${chanID}/messages/${msgID}/reactions/${reaction}`;
module.exports.CHANNEL_MESSAGE_REACTION_USER = (chanID, msgID, reaction, userID) => `/channels/${chanID}/messages/${msgID}/reactions/${reaction}/${userID}`;
module.exports.CHANNEL_MESSAGE_REACTIONS =                       (chanID, msgID) => `/channels/${chanID}/messages/${msgID}/reactions`;
module.exports.CHANNEL_MESSAGE =                                 (chanID, msgID) => `/channels/${chanID}/messages/${msgID}`;
module.exports.CHANNEL_MESSAGES =                                       (chanID) => `/channels/${chanID}/messages`;
module.exports.CHANNEL_MESSAGES_SEARCH =                                (chanID) => `/channels/${chanID}/messages/search`;
module.exports.CHANNEL_PERMISSION =                             (chanID, overID) => `/channels/${chanID}/permissions/${overID}`;
module.exports.CHANNEL_PERMISSIONS =                                    (chanID) => `/channels/${chanID}/permissions`;
module.exports.CHANNEL_PIN =                                     (chanID, msgID) => `/channels/${chanID}/pins/${msgID}`;
module.exports.CHANNEL_PINS =                                           (chanID) => `/channels/${chanID}/pins`;
module.exports.CHANNEL_RECIPIENT =                             (groupID, userID) => `/channels/${groupID}/recipients/${userID}`;
module.exports.CHANNEL_TYPING =                                         (chanID) => `/channels/${chanID}/typing`;
module.exports.CHANNEL_WEBHOOKS =                                       (chanID) => `/channels/${chanID}/webhooks`;
module.exports.CHANNELS =                                                           "/channels";
module.exports.GATEWAY =                                                            "/gateway";
module.exports.GATEWAY_BOT =                                                        "/gateway/bot";
module.exports.CLUB =                                                 (clubID) => `/clubs/${clubID}`;
module.exports.CLUB_AUDIT_LOGS =                                      (clubID) => `/clubs/${clubID}/audit-logs`;
module.exports.CLUB_BAN =                                   (clubID, memberID) => `/clubs/${clubID}/bans/${memberID}`;
module.exports.CLUB_BANS =                                            (clubID) => `/clubs/${clubID}/bans`;
module.exports.CLUB_CHANNELS =                                        (clubID) => `/clubs/${clubID}/channels`;
module.exports.CLUB_EMBED =                                           (clubID) => `/clubs/${clubID}/embed`;
module.exports.CLUB_EMOJI =                                  (clubID, emojiID) => `/clubs/${clubID}/emojis/${emojiID}`;
module.exports.CLUB_EMOJIS =                                          (clubID) => `/clubs/${clubID}/emojis`;
module.exports.CLUB_INTEGRATION =                             (clubID, inteID) => `/clubs/${clubID}/integrations/${inteID}`;
module.exports.CLUB_INTEGRATION_SYNC =                        (clubID, inteID) => `/clubs/${clubID}/integrations/${inteID}/sync`;
module.exports.CLUB_INTEGRATIONS =                                    (clubID) => `/clubs/${clubID}/integrations`;
module.exports.CLUB_INVITES =                                         (clubID) => `/clubs/${clubID}/invites`;
module.exports.CLUB_VANITY_URL =                                      (clubID) => `/clubs/${clubID}/vanity-url`;
module.exports.CLUB_MEMBER =                                (clubID, memberID) => `/clubs/${clubID}/members/${memberID}`;
module.exports.CLUB_MEMBER_NICK =                           (clubID, memberID) => `/clubs/${clubID}/members/${memberID}/nick`;
module.exports.CLUB_MEMBER_ROLE =                   (clubID, memberID, roleID) => `/clubs/${clubID}/members/${memberID}/roles/${roleID}`;
module.exports.CLUB_MEMBERS =                                         (clubID) => `/clubs/${clubID}/members`;
module.exports.CLUB_MEMBERS_SEARCH =                                  (clubID) => `/clubs/${clubID}/members/search`;
module.exports.CLUB_MESSAGES_SEARCH =                                 (clubID) => `/clubs/${clubID}/messages/search`;
module.exports.CLUB_PREVIEW =                                         (clubID) => `/clubs/${clubID}/preview`;
module.exports.CLUB_PRUNE =                                           (clubID) => `/clubs/${clubID}/prune`;
module.exports.CLUB_ROLE =                                    (clubID, roleID) => `/clubs/${clubID}/roles/${roleID}`;
module.exports.CLUB_ROLES =                                           (clubID) => `/clubs/${clubID}/roles`;
module.exports.CLUB_VOICE_REGIONS =                                   (clubID) => `/clubs/${clubID}/regions`;
module.exports.CLUB_WEBHOOKS =                                        (clubID) => `/clubs/${clubID}/webhooks`;
module.exports.CLUB_WIDGET =                                          (clubID) => `/clubs/${clubID}/widget`;
module.exports.CLUBS =                                                             "/clubs";
module.exports.INVITE =                                               (inviteID) => `/invite/${inviteID}`;
module.exports.OAUTH2_APPLICATION =                                      (appID) => `/oauth2/applications/${appID}`;
module.exports.USER =                                                   (userID) => `/users/${userID}`;
module.exports.USER_BILLING =                                           (userID) => `/users/${userID}/billing`;
module.exports.USER_BILLING_PAYMENTS =                                  (userID) => `/users/${userID}/billing/payments`;
module.exports.USER_BILLING_PREMIUM_SUBSCRIPTION =                      (userID) => `/users/${userID}/billing/premium-subscription`;
module.exports.USER_CHANNELS =                                          (userID) => `/users/${userID}/channels`;
module.exports.USER_CONNECTIONS =                                       (userID) => `/users/${userID}/connections`;
module.exports.USER_CONNECTION_PLATFORM =                 (userID, platform, id) => `/users/${userID}/connections/${platform}/${id}`;
module.exports.USER_CLUB =                                    (userID, clubID) => `/users/${userID}/clubs/${clubID}`;
module.exports.USER_CLUBS =                                            (userID) => `/users/${userID}/clubs`;
module.exports.USER_MFA_CODES =                                         (userID) => `/users/${userID}/mfa/codes`;
module.exports.USER_MFA_TOTP_DISABLE =                                  (userID) => `/users/${userID}/mfa/totp/disable`;
module.exports.USER_MFA_TOTP_ENABLE =                                   (userID) => `/users/${userID}/mfa/totp/enable`;
module.exports.USER_NOTE =                                    (userID, targetID) => `/users/${userID}/note/${targetID}`;
module.exports.USER_PROFILE =                                           (userID) => `/users/${userID}/profile`;
module.exports.USER_RELATIONSHIP =                               (userID, relID) => `/users/${userID}/relationships/${relID}`;
module.exports.USER_SETTINGS =                                          (userID) => `/users/${userID}/settings`;
module.exports.USERS =                                                              "/users";
module.exports.VOICE_REGIONS =                                                      "/voice/regions";
module.exports.WEBHOOK =                                                (hookID) => `/webhooks/${hookID}`;
module.exports.WEBHOOK_SLACK =                                          (hookID) => `/webhooks/${hookID}/slack`;
module.exports.WEBHOOK_TOKEN =                                   (hookID, token) => `/webhooks/${hookID}/${token}`;
module.exports.WEBHOOK_TOKEN_SLACK =                             (hookID, token) => `/webhooks/${hookID}/${token}/slack`;

// CDN Endpoints
module.exports.CHANNEL_ICON =                                 (chanID, chanIcon) => `/channel-icons/${chanID}/${chanIcon}`;
module.exports.CUSTOM_EMOJI =                                          (emojiID) => `/emojis/${emojiID}`;
module.exports.DEFAULT_USER_AVATAR =                         (userDiscriminator) => `/embed/avatars/${userDiscriminator}`;
module.exports.CLUB_BANNER =                             (clubID, clubBanner) => `/banners/${clubID}/${clubBanner}`;
module.exports.CLUB_DISCOVERY_SPLASH =          (clubID, clubDiscoverySplash) => `/discovery-splashes/${clubID}/${clubDiscoverySplash}`;
module.exports.CLUB_ICON =                                 (clubID, clubIcon) => `/icons/${clubID}/${clubIcon}`;
module.exports.CLUB_SPLASH =                             (clubID, clubSplash) => `/splashes/${clubID}/${clubSplash}`;
module.exports.USER_AVATAR =                                (userID, userAvatar) => `/avatars/${userID}/${userAvatar}`;

// Client Endpoints
module.exports.MESSAGE_LINK =                    (clubID, channelID, messageID) => `/channels/${clubID}/${channelID}/${messageID}`;
